--> The item prices of Saidoro's "Sane Magic Item Prices" (shared for use with
--> credit to the author), taken from the guide's five price tables as the
--> 5etools homebrew repository holds them. They belong to the instance, not
--> to a campaign, so a fresh instance has them without a seed. The search
--> index holds each item once, with no campaign; every campaign's search
--> finds it.
CREATE TABLE `item_prices` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`price_gp` integer NOT NULL,
	`list` text NOT NULL,
	`note` text DEFAULT '' NOT NULL,
	`rev` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "item_prices_list_check" CHECK(`list` in ('consumable', 'combat', 'noncombat', 'summoning', 'gamechanging'))
);
--> statement-breakpoint
INSERT INTO `item_prices` (`id`, `name`, `price_gp`, `list`, `note`) VALUES
	('spell-scroll-cantrip', 'Spell Scroll, Cantrip', 10, 'consumable', ''),
	('sovereign-glue', 'Sovereign Glue', 400, 'consumable', ''),
	('1-ammunition', '+1 ammunition', 25, 'consumable', 'each'),
	('horn-of-blasting', 'Horn of Blasting', 450, 'consumable', ''),
	('potion-of-healing', 'Potion of Healing', 50, 'consumable', ''),
	('potion-of-superior-healing', 'Potion of Superior Healing', 450, 'consumable', ''),
	('quaal-s-feather-token-anchor', 'Quaal''s Feather Token, Anchor', 50, 'consumable', ''),
	('dust-of-sneezing-and-choking', 'Dust of Sneezing and Choking', 480, 'consumable', ''),
	('spell-scroll-level-1', 'Spell Scroll, Level 1', 60, 'consumable', ''),
	('necklace-of-fireballs-two-beads', 'Necklace of Fireballs (Two beads)', 480, 'consumable', ''),
	('philter-of-love', 'Philter of Love', 90, 'consumable', ''),
	('oil-of-slipperiness', 'Oil of Slipperiness', 480, 'consumable', ''),
	('2-ammunition', '+2 ammunition', 100, 'consumable', 'each'),
	('potion-of-flying', 'Potion of Flying', 500, 'consumable', ''),
	('potion-of-poison', 'Potion of Poison', 100, 'consumable', ''),
	('arrow-of-slaying', 'Arrow of Slaying', 600, 'consumable', 'each'),
	('dust-of-dryness', 'Dust of Dryness', 120, 'consumable', '1 pellet'),
	('spell-scroll-level-5', 'Spell Scroll, Level 5', 640, 'consumable', ''),
	('elixir-of-health', 'Elixir of Health', 120, 'consumable', ''),
	('bead-of-force', 'Bead of Force', 960, 'consumable', ''),
	('keoghtom-s-ointment', 'Keoghtom''s Ointment', 120, 'consumable', 'per dose'),
	('elemental-gem', 'Elemental Gem', 960, 'consumable', ''),
	('spell-scroll-level-2', 'Spell Scroll, Level 2', 120, 'consumable', ''),
	('necklace-of-fireballs-three-beads', 'Necklace of Fireballs (Three beads)', 960, 'consumable', ''),
	('potion-of-fire-breath', 'Potion of Fire Breath', 150, 'consumable', ''),
	('potion-of-clairvoyance', 'Potion of Clairvoyance', 960, 'consumable', ''),
	('potion-of-greater-healing', 'Potion of Greater Healing', 150, 'consumable', ''),
	('potion-of-vitality', 'Potion of Vitality', 960, 'consumable', ''),
	('potion-of-climbing', 'Potion of Climbing', 180, 'consumable', ''),
	('spell-scroll-level-6', 'Spell Scroll, Level 6', 1280, 'consumable', ''),
	('potion-of-heroism', 'Potion of Heroism', 180, 'consumable', ''),
	('potion-of-supreme-healing', 'Potion of Supreme Healing', 1350, 'consumable', ''),
	('potion-of-invisibility', 'Potion of Invisibility', 180, 'consumable', ''),
	('chime-of-opening', 'Chime of Opening', 1500, 'consumable', ''),
	('potion-of-mind-reading', 'Potion of Mind Reading', 180, 'consumable', ''),
	('necklace-of-fireballs-four-beads', 'Necklace of Fireballs (Four beads)', 1600, 'consumable', ''),
	('potion-of-water-breathing', 'Potion of Water Breathing', 180, 'consumable', ''),
	('oil-of-etherealness', 'Oil of Etherealness', 1920, 'consumable', ''),
	('scroll-of-protection', 'Scroll of Protection', 180, 'consumable', ''),
	('ioun-stone-absorption', 'Ioun Stone, Absorption', 2400, 'consumable', ''),
	('nolzur-s-marvelous-pigments', 'Nolzur''s Marvelous Pigments', 200, 'consumable', ''),
	('spell-scroll-level-7', 'Spell Scroll, Level 7', 2560, 'consumable', ''),
	('potion-of-animal-friendship', 'Potion of Animal Friendship', 200, 'consumable', ''),
	('quaal-s-feather-token-bird', 'Quaal''s Feather Token, Bird', 3000, 'consumable', ''),
	('spell-scroll-level-3', 'Spell Scroll, Level 3', 200, 'consumable', ''),
	('quaal-s-feather-token-swan-boat', 'Quaal''s Feather Token, Swan Boat', 3000, 'consumable', ''),
	('quaal-s-feather-token-fan', 'Quaal''s Feather Token, Fan', 250, 'consumable', ''),
	('oil-of-sharpness', 'Oil of Sharpness', 3200, 'consumable', ''),
	('quaal-s-feather-token-whip', 'Quaal''s Feather Token, Whip', 250, 'consumable', ''),
	('necklace-of-fireballs-five-beads', 'Necklace of Fireballs (Five beads)', 3840, 'consumable', ''),
	('potion-of-diminution', 'Potion of Diminution', 270, 'consumable', ''),
	('potion-of-invulnerability', 'Potion of Invulnerability', 3840, 'consumable', ''),
	('potion-of-growth', 'Potion of Growth', 270, 'consumable', ''),
	('gem-of-brightness', 'Gem of Brightness', 5000, 'consumable', ''),
	('dust-of-disappearance', 'Dust of Disappearance', 300, 'consumable', ''),
	('spell-scroll-level-8', 'Spell Scroll, Level 8', 5120, 'consumable', ''),
	('necklace-of-fireballs-one-bead', 'Necklace of Fireballs (One bead)', 300, 'consumable', ''),
	('deck-of-illusions', 'Deck of Illusions', 6120, 'consumable', ''),
	('potion-of-gaseous-form', 'Potion of Gaseous Form', 300, 'consumable', ''),
	('necklace-of-fireballs-six-beads', 'Necklace of Fireballs (Six beads)', 7680, 'consumable', ''),
	('potion-of-resistance', 'Potion of Resistance', 300, 'consumable', ''),
	('spell-scroll-level-9', 'Spell Scroll, Level 9', 10240, 'consumable', ''),
	('universal-solvent', 'Universal Solvent', 300, 'consumable', ''),
	('ioun-stone-greater-absorption', 'Ioun Stone, Greater Absorption', 31000, 'consumable', ''),
	('spell-scroll-level-4', 'Spell Scroll, Level 4', 320, 'consumable', ''),
	('rod-of-absorption', 'Rod of Absorption', 50000, 'consumable', ''),
	('3-ammunition', '+3 ammunition', 400, 'consumable', 'each'),
	('talisman-of-ultimate-evil', 'Talisman of Ultimate Evil', 61440, 'consumable', ''),
	('potion-of-speed', 'Potion of Speed', 400, 'consumable', ''),
	('talisman-of-pure-good', 'Talisman of Pure Good', 71680, 'consumable', ''),
	('vicious-weapon', 'Vicious Weapon', 350, 'combat', ''),
	('brooch-of-shielding', 'Brooch of Shielding', 7500, 'combat', ''),
	('adamantine-armor', 'Adamantine Armor', 500, 'combat', ''),
	('amulet-of-health', 'Amulet of Health', 8000, 'combat', ''),
	('mithral-armor', 'Mithral Armor', 800, 'combat', ''),
	('dragon-slayer', 'Dragon Slayer', 8000, 'combat', ''),
	('1-weapon', '+1 Weapon', 1000, 'combat', ''),
	('gauntlets-of-ogre-power', 'Gauntlets of Ogre Power', 8000, 'combat', ''),
	('sword-of-life-stealing', 'Sword of Life Stealing', 1000, 'combat', ''),
	('headband-of-intellect', 'Headband of Intellect', 8000, 'combat', ''),
	('ioun-stone-protection', 'Ioun Stone, Protection', 1200, 'combat', ''),
	('mace-of-disruption', 'Mace of Disruption', 8000, 'combat', ''),
	('1-wand-of-the-war-mage', '+1 wand of the war mage', 1200, 'combat', ''),
	('mace-of-terror', 'Mace of Terror', 8000, 'combat', ''),
	('bracers-of-archery', 'Bracers of Archery', 1500, 'combat', ''),
	('nine-lives-stealer', 'Nine Lives Stealer', 8000, 'combat', 'fully charged'),
	('circlet-of-blasting', 'Circlet of Blasting', 1500, 'combat', ''),
	('wand-of-magic-missiles', 'Wand of Magic Missiles', 8000, 'combat', ''),
	('javelin-of-lightning', 'Javelin of Lightning', 1500, 'combat', ''),
	('wand-of-web', 'Wand of Web', 8000, 'combat', ''),
	('prayer-bead-smiting', 'Prayer Bead - Smiting', 1500, 'combat', ''),
	('staff-of-thunder-and-lightning', 'Staff of Thunder and Lightning', 10000, 'combat', ''),
	('wind-fan', 'Wind Fan', 1500, 'combat', ''),
	('wand-of-binding', 'Wand of Binding', 10000, 'combat', ''),
	('sword-of-sharpness', 'Sword of Sharpness', 1700, 'combat', ''),
	('wand-of-fear', 'Wand of Fear', 10000, 'combat', ''),
	('staff-of-the-adder', 'Staff of the Adder', 1800, 'combat', ''),
	('ioun-stone-awareness', 'Ioun Stone, Awareness', 12000, 'combat', ''),
	('dancing-sword', 'Dancing Sword', 2000, 'combat', ''),
	('1-rod-of-the-pact-keeper', '+1 rod of the pact keeper', 12000, 'combat', ''),
	('glamoured-studded-leather', 'Glamoured Studded Leather', 2000, 'combat', ''),
	('staff-of-charming', 'Staff of Charming', 12000, 'combat', ''),
	('pipes-of-the-sewers', 'Pipes of the Sewers', 2000, 'combat', ''),
	('sun-blade', 'Sun Blade', 12000, 'combat', ''),
	('prayer-bead-bless', 'Prayer Bead - Bless', 2000, 'combat', ''),
	('staff-of-healing', 'Staff of Healing', 13000, 'combat', ''),
	('saddle-of-the-cavalier', 'Saddle of the Cavalier', 2000, 'combat', ''),
	('ring-of-shooting-stars', 'Ring of Shooting Stars', 14000, 'combat', ''),
	('sword-of-wounding', 'Sword of Wounding', 2000, 'combat', ''),
	('ioun-stone-mastery', 'Ioun Stone, Mastery', 15000, 'combat', ''),
	('frost-brand', 'Frost Brand', 2200, 'combat', ''),
	('3-weapon', '+3 Weapon', 16000, 'combat', ''),
	('dagger-of-venom', 'Dagger of Venom', 2500, 'combat', ''),
	('hammer-of-thunderbolts', 'Hammer of Thunderbolts', 16000, 'combat', ''),
	('gloves-of-missile-snaring', 'Gloves of Missile Snaring', 3000, 'combat', ''),
	('2-rod-of-the-pact-keeper', '+2 rod of the pact keeper', 16000, 'combat', ''),
	('ioun-stone-agility', 'Ioun Stone, Agility', 3000, 'combat', ''),
	('staff-of-fire', 'Staff of Fire', 16000, 'combat', ''),
	('ioun-stone-fortitude', 'Ioun Stone, Fortitude', 3000, 'combat', ''),
	('staff-of-swarming-insects', 'Staff of Swarming Insects', 16000, 'combat', ''),
	('ioun-stone-insight', 'Ioun Stone, Insight', 3000, 'combat', ''),
	('wand-of-paralysis', 'Wand of Paralysis', 16000, 'combat', ''),
	('ioun-stone-intellect', 'Ioun Stone, Intellect', 3000, 'combat', ''),
	('ring-of-fire-elemental-command', 'Ring of Fire Elemental Command', 17000, 'combat', ''),
	('ioun-stone-leadership', 'Ioun Stone, Leadership', 3000, 'combat', ''),
	('dwarven-thrower', 'Dwarven Thrower', 18000, 'combat', ''),
	('ioun-stone-strength', 'Ioun Stone, Strength', 3000, 'combat', ''),
	('3-wand-of-the-war-mage', '+3 wand of the war mage', 19200, 'combat', ''),
	('staff-of-withering', 'Staff of Withering', 3000, 'combat', ''),
	('efreeti-chain', 'Efreeti Chain', 20000, 'combat', ''),
	('cloak-of-protection', 'Cloak of Protection', 3500, 'combat', ''),
	('ring-of-free-action', 'Ring of Free Action', 20000, 'combat', ''),
	('oathbow', 'Oathbow', 3500, 'combat', ''),
	('sentinel-shield', 'Sentinel Shield', 20000, 'combat', ''),
	('ring-of-protection', 'Ring of Protection', 3500, 'combat', ''),
	('staff-of-striking', 'Staff of Striking', 21000, 'combat', ''),
	('2-weapon', '+2 Weapon', 4000, 'combat', ''),
	('ring-of-spell-storing', 'Ring of Spell Storing', 24000, 'combat', ''),
	('boots-of-speed', 'Boots of Speed', 4000, 'combat', ''),
	('vorpal-sword', 'Vorpal Sword', 24000, 'combat', ''),
	('dragon-scale-mail', 'Dragon Scale Mail', 4000, 'combat', ''),
	('ring-of-water-elemental-command', 'Ring of Water Elemental Command', 25000, 'combat', ''),
	('elven-chain', 'Elven Chain', 4000, 'combat', ''),
	('rod-of-alertness', 'Rod of Alertness', 25000, 'combat', ''),
	('ioun-stone-regeneration', 'Ioun Stone, Regeneration', 4000, 'combat', ''),
	('staff-of-frost', 'Staff of Frost', 26000, 'combat', ''),
	('iron-bands-of-bilarro', 'Iron Bands of Bilarro', 4000, 'combat', ''),
	('instrument-of-the-bards-fochlucan-bandore', 'Instrument of the Bards, Fochlucan Bandore', 26500, 'combat', ''),
	('prayer-bead-curing', 'Prayer Bead - Curing', 4000, 'combat', ''),
	('instrument-of-the-bards-mac-fuirmidh-cittern', 'Instrument of the Bards, Mac-Fuirmidh Cittern', 27000, 'combat', ''),
	('rope-of-entanglement', 'Rope of Entanglement', 4000, 'combat', ''),
	('rod-of-lordly-might', 'Rod of Lordly Might', 28000, 'combat', ''),
	('wand-of-enemy-detection', 'Wand of Enemy Detection', 4000, 'combat', ''),
	('3-rod-of-the-pact-keeper', '+3 rod of the pact keeper', 28000, 'combat', ''),
	('stone-of-good-luck', 'Stone of Good Luck', 4200, 'combat', ''),
	('instrument-of-the-bards-doss-lute', 'Instrument of the Bards, Doss Lute', 28500, 'combat', ''),
	('2-wand-of-the-war-mage', '+2 wand of the war mage', 4800, 'combat', ''),
	('instrument-of-the-bards-canaith-mandolin', 'Instrument of the Bards, Canaith Mandolin', 30000, 'combat', ''),
	('flame-tongue', 'Flame Tongue', 5000, 'combat', ''),
	('mantle-of-spell-resistance', 'Mantle of Spell Resistance', 30000, 'combat', ''),
	('periapt-of-wound-closure', 'Periapt of Wound Closure', 5000, 'combat', ''),
	('ring-of-spell-turning', 'Ring of Spell Turning', 30000, 'combat', ''),
	('ring-of-evasion', 'Ring of Evasion', 5000, 'combat', ''),
	('prayer-bead-favor', 'Prayer Bead - Favor', 32000, 'combat', ''),
	('ring-of-the-ram', 'Ring of the Ram', 5000, 'combat', ''),
	('wand-of-fireballs', 'Wand of Fireballs', 32000, 'combat', ''),
	('tentacle-rod', 'Tentacle Rod', 5000, 'combat', ''),
	('wand-of-lightning-bolts', 'Wand of Lightning Bolts', 32000, 'combat', ''),
	('animated-shield', 'Animated Shield', 6000, 'combat', ''),
	('wand-of-polymorph', 'Wand of Polymorph', 32000, 'combat', ''),
	('armor-of-resistance', 'Armor of Resistance', 6000, 'combat', ''),
	('instrument-of-the-bards-cli-lyre', 'Instrument of the Bards, Cli Lyre', 35000, 'combat', ''),
	('arrow-catching-shield', 'Arrow-Catching Shield', 6000, 'combat', ''),
	('scarab-of-protection', 'Scarab of Protection', 36000, 'combat', ''),
	('belt-of-dwarvenkind', 'Belt of Dwarvenkind', 6000, 'combat', ''),
	('sword-of-answering', 'Sword of Answering', 36000, 'combat', ''),
	('bracers-of-defense', 'Bracers of Defense', 6000, 'combat', ''),
	('staff-of-the-woodlands', 'Staff of the Woodlands', 44000, 'combat', ''),
	('ioun-stone-reserve', 'Ioun Stone, Reserve', 6000, 'combat', ''),
	('spellguard-shield', 'Spellguard Shield', 50000, 'combat', ''),
	('pearl-of-power', 'Pearl of Power', 6000, 'combat', ''),
	('cloak-of-displacement', 'Cloak of Displacement', 60000, 'combat', ''),
	('pipes-of-haunting', 'Pipes of Haunting', 6000, 'combat', ''),
	('robe-of-stars', 'Robe of Stars', 60000, 'combat', ''),
	('ring-of-resistance', 'Ring of Resistance', 6000, 'combat', ''),
	('weapon-of-warning', 'Weapon of Warning', 60000, 'combat', ''),
	('robe-of-scintillating-colors', 'Robe of Scintillating Colors', 6000, 'combat', ''),
	('prayer-bead-wind-walking', 'Prayer Bead - Wind Walking', 96000, 'combat', ''),
	('scimitar-of-speed', 'Scimitar of Speed', 6000, 'combat', ''),
	('instrument-of-the-bards-anstruth-harp', 'Instrument of the Bards, Anstruth Harp', 109000, 'combat', ''),
	('shield-of-missile-attraction', 'Shield of Missile Attraction', 6000, 'combat', ''),
	('instrument-of-the-bards-ollamh-harp', 'Instrument of the Bards, Ollamh Harp', 125000, 'combat', ''),
	('giant-slayer', 'Giant Slayer', 7000, 'combat', ''),
	('prayer-bead-summons', 'Prayer Bead - Summons', 128000, 'combat', ''),
	('mace-of-smiting', 'Mace of Smiting', 7000, 'combat', ''),
	('holy-avenger', 'Holy Avenger', 165000, 'combat', ''),
	('helm-of-comprehending-languages', 'Helm of Comprehending Languages', 500, 'noncombat', ''),
	('boots-of-striding-and-springing', 'Boots of Striding and Springing', 5000, 'noncombat', ''),
	('driftglobe', 'Driftglobe', 750, 'noncombat', ''),
	('cloak-of-arachnida', 'Cloak of Arachnida', 5000, 'noncombat', ''),
	('trident-of-fish-command', 'Trident of Fish Command', 800, 'noncombat', ''),
	('cloak-of-elvenkind', 'Cloak of Elvenkind', 5000, 'noncombat', ''),
	('cap-of-water-breathing', 'Cap of Water Breathing', 1000, 'noncombat', ''),
	('gloves-of-thievery', 'Gloves of Thievery', 5000, 'noncombat', ''),
	('eversmoking-bottle', 'Eversmoking Bottle', 1000, 'noncombat', ''),
	('hat-of-disguise', 'Hat of Disguise', 5000, 'noncombat', ''),
	('quiver-of-ehlonna', 'Quiver of Ehlonna', 1000, 'noncombat', ''),
	('horseshoes-of-speed', 'Horseshoes of Speed', 5000, 'noncombat', ''),
	('ioun-stone-sustenance', 'Ioun Stone, Sustenance', 1000, 'noncombat', ''),
	('immovable-rod', 'Immovable Rod', 5000, 'noncombat', ''),
	('ring-of-warmth', 'Ring of Warmth', 1000, 'noncombat', ''),
	('lantern-of-revealing', 'Lantern of Revealing', 5000, 'noncombat', ''),
	('goggles-of-night', 'Goggles of Night', 1500, 'noncombat', ''),
	('periapt-of-health', 'Periapt of Health', 5000, 'noncombat', ''),
	('horseshoes-of-a-zephyr', 'Horseshoes of a Zephyr', 1500, 'noncombat', ''),
	('periapt-of-proof-against-poison', 'Periapt of Proof Against Poison', 5000, 'noncombat', ''),
	('mariner-s-armor', 'Mariner''s Armor', 1500, 'noncombat', ''),
	('slippers-of-spider-climbing', 'Slippers of Spider Climbing', 5000, 'noncombat', ''),
	('necklace-of-adaptation', 'Necklace of Adaptation', 1500, 'noncombat', ''),
	('cloak-of-the-bat', 'Cloak of the Bat', 6000, 'noncombat', ''),
	('ring-of-water-walking', 'Ring of Water Walking', 1500, 'noncombat', ''),
	('cloak-of-the-manta-ray', 'Cloak of the Manta Ray', 6000, 'noncombat', ''),
	('wand-of-magic-detection', 'Wand of Magic Detection', 1500, 'noncombat', ''),
	('ring-of-x-ray-vision', 'Ring of X-Ray Vision', 6000, 'noncombat', ''),
	('wand-of-secrets', 'Wand of Secrets', 1500, 'noncombat', ''),
	('cape-of-the-mountebank', 'Cape of the Mountebank', 8000, 'noncombat', ''),
	('gloves-of-swimming-and-climbing', 'Gloves of Swimming and Climbing', 2000, 'noncombat', ''),
	('portable-hole', 'Portable Hole', 8000, 'noncombat', ''),
	('heward-s-handy-haversack', 'Heward''s Handy Haversack', 2000, 'noncombat', ''),
	('apparatus-of-kwalish', 'Apparatus of Kwalish', 10000, 'noncombat', ''),
	('rope-of-climbing', 'Rope of Climbing', 2000, 'noncombat', ''),
	('boots-of-the-winterlands', 'Boots of the Winterlands', 10000, 'noncombat', ''),
	('ring-of-feather-falling', 'Ring of Feather Falling', 2000, 'noncombat', ''),
	('folding-boat', 'Folding Boat', 10000, 'noncombat', ''),
	('boots-of-elvenkind', 'Boots of Elvenkind', 2500, 'noncombat', ''),
	('ring-of-invisibility', 'Ring of Invisibility', 10000, 'noncombat', ''),
	('eyes-of-minute-seeing', 'Eyes of Minute Seeing', 2500, 'noncombat', ''),
	('helm-of-telepathy', 'Helm of Telepathy', 12000, 'noncombat', ''),
	('eyes-of-the-eagle', 'Eyes of the Eagle', 2500, 'noncombat', ''),
	('cube-of-force', 'Cube of Force', 16000, 'noncombat', ''),
	('ring-of-jumping', 'Ring of Jumping', 2500, 'noncombat', ''),
	('ring-of-mind-shielding', 'Ring of Mind Shielding', 16000, 'noncombat', ''),
	('dimensional-shackles', 'Dimensional Shackles', 3000, 'noncombat', ''),
	('rod-of-rulership', 'Rod of Rulership', 16000, 'noncombat', ''),
	('eyes-of-charming', 'Eyes of Charming', 3000, 'noncombat', ''),
	('mirror-of-life-trapping', 'Mirror of Life Trapping', 18000, 'noncombat', ''),
	('medallion-of-thoughts', 'Medallion of Thoughts', 3000, 'noncombat', ''),
	('amulet-of-proof-against-detection-and-location', 'Amulet of Proof Against Detection and Location', 20000, 'noncombat', ''),
	('ring-of-swimming', 'Ring of Swimming', 3000, 'noncombat', ''),
	('robe-of-eyes', 'Robe of Eyes', 30000, 'noncombat', ''),
	('bag-of-holding', 'Bag of Holding', 4000, 'noncombat', ''),
	('gem-of-seeing', 'Gem of Seeing', 32000, 'noncombat', ''),
	('boots-of-levitation', 'Boots of Levitation', 4000, 'noncombat', ''),
	('plate-armor-of-etherealness', 'Plate Armor of Etherealness', 48000, 'noncombat', ''),
	('ring-of-animal-influence', 'Ring of Animal Influence', 4000, 'noncombat', ''),
	('ivory-goat-travail', 'Ivory Goat (Travail)', 400, 'summoning', ''),
	('bowl-of-commanding-water-elementals', 'Bowl of Commanding Water Elementals', 8000, 'summoning', ''),
	('golden-lion', 'Golden Lion', 600, 'summoning', 'each'),
	('brazier-of-commanding-fire-elementals', 'Brazier of Commanding Fire Elementals', 8000, 'summoning', ''),
	('ivory-goat-traveling', 'Ivory Goat (Traveling)', 1000, 'summoning', ''),
	('censer-of-controlling-air-elementals', 'Censer of Controlling Air Elementals', 8000, 'summoning', ''),
	('staff-of-the-python', 'Staff of the Python', 2000, 'summoning', ''),
	('stone-of-controlling-earth-elementals', 'Stone of Controlling Earth Elementals', 8000, 'summoning', ''),
	('onyx-dog', 'Onyx Dog', 3000, 'summoning', ''),
	('horn-of-valhalla-brass', 'Horn of Valhalla, Brass', 8400, 'summoning', ''),
	('silver-raven', 'Silver Raven', 5000, 'summoning', ''),
	('horn-of-valhalla-bronze', 'Horn of Valhalla, Bronze', 11200, 'summoning', ''),
	('horn-of-valhalla-silver', 'Horn of Valhalla, Silver', 5600, 'summoning', ''),
	('horn-of-valhalla-iron', 'Horn of Valhalla, Iron', 14000, 'summoning', ''),
	('marble-elephant', 'Marble Elephant', 6000, 'summoning', ''),
	('ivory-goat-terror', 'Ivory Goat (Terror)', 20000, 'summoning', ''),
	('1-armor', '+1 Armor', 1500, 'gamechanging', ''),
	('talisman-of-the-sphere', 'Talisman of the Sphere', 20000, 'gamechanging', ''),
	('1-shield', '+1 Shield', 1500, 'gamechanging', ''),
	('3-armor', '+3 Armor', 24000, 'gamechanging', ''),
	('sending-stones', 'Sending Stones', 2000, 'gamechanging', ''),
	('3-shield', '+3 Shield', 24000, 'gamechanging', ''),
	('wings-of-flying', 'Wings of Flying', 5000, 'gamechanging', ''),
	('defender', 'Defender', 24000, 'gamechanging', ''),
	('alchemy-jug', 'Alchemy Jug', 6000, 'gamechanging', ''),
	('ring-of-earth-elemental-command', 'Ring of Earth Elemental Command', 31000, 'gamechanging', ''),
	('2-armor', '+2 Armor', 6000, 'gamechanging', ''),
	('robe-of-the-archmagi', 'Robe of the Archmagi', 34000, 'gamechanging', ''),
	('2-shield', '+2 Shield', 6000, 'gamechanging', ''),
	('ring-of-air-elemental-command', 'Ring of Air Elemental Command', 35000, 'gamechanging', ''),
	('ebony-fly', 'Ebony Fly', 6000, 'gamechanging', ''),
	('cubic-gate', 'Cubic Gate', 40000, 'gamechanging', ''),
	('bronze-griffon', 'Bronze Griffon', 8000, 'gamechanging', ''),
	('crystal-ball', 'Crystal Ball', 50000, 'gamechanging', ''),
	('broom-of-flying', 'Broom of Flying', 8000, 'gamechanging', ''),
	('helm-of-teleportation', 'Helm of Teleportation', 64000, 'gamechanging', ''),
	('serpentine-owl', 'Serpentine Owl', 8000, 'gamechanging', ''),
	('daern-s-instant-fortress', 'Daern''s Instant Fortress', 75000, 'gamechanging', ''),
	('winged-boots', 'Winged Boots', 8000, 'gamechanging', ''),
	('ring-of-telekinesis', 'Ring of Telekinesis', 80000, 'gamechanging', ''),
	('dwarven-plate', 'Dwarven Plate', 9000, 'gamechanging', ''),
	('cloak-of-invisibility', 'Cloak of Invisibility', 80000, 'gamechanging', ''),
	('potion-of-longevity', 'Potion of Longevity', 9000, 'gamechanging', ''),
	('rod-of-security', 'Rod of Security', 90000, 'gamechanging', ''),
	('carpet-of-flying', 'Carpet of Flying', 12000, 'gamechanging', ''),
	('staff-of-power', 'Staff of Power', 95500, 'gamechanging', ''),
	('ring-of-regeneration', 'Ring of Regeneration', 12000, 'gamechanging', ''),
	('obsidian-steed', 'Obsidian Steed', 128000, 'gamechanging', ''),
	('sphere-of-annihilation', 'Sphere of Annihilation', 15000, 'gamechanging', ''),
	('decanter-of-endless-water', 'Decanter of Endless Water', 135000, 'gamechanging', ''),
	('armor-of-invulnerability', 'Armor of Invulnerability', 18000, 'gamechanging', ''),
	('amulet-of-the-planes', 'Amulet of the Planes', 160000, 'gamechanging', '');--> statement-breakpoint
INSERT INTO `search_fts` (`title`, `ref`, `tags`, `body`, `campaign_id`, `kind`, `entity_id`)
SELECT `name`, `id`, '', '', NULL, 'item-price', `id` FROM `item_prices`;
